### ISSUE TITLE
Create variable length integer functions in the low-level marshalling library

### ISSUE THREAD

**Issue by cliffg-softwarelibre** [connectivecpp/utility-rack#15]
Create functions to marshall and unmarshall a variable length integer. The "append" / marshall function will take an integer in native format, and create a 1 or 2 or 3 or 4 (or more) byte integer. The first byte will contain values from 0-127, and the MSB (most significant bit) will designate whether another byte is needed (for larger values). The "extract" / unmarshall function will perform the converse.

One usage of this will be in the MQTT wire protocol (see section 1.5.5 of the MQTT 5.0 spec).

A good place for these functions is in the "extract_append_val.hpp" header in the marshall directory of the utility-rack repo.

**Comment by oxenran** [comment]
I think I found a similar example here.
https://techoverflow.net/2013/01/25/efficiently-encoding-variable-length-integers-in-cc/
In this example, they're setting a byte flag.  Is that something that needs to happen in this case?

**Comment by cliffg-softwarelibre** [comment]
The merged files look good - a static_assert was added by me to the production functions so that only unsigned integers can be used, unit tests modified accordingly, and some additional unit test round-trips added. Good work!
