### ISSUE TITLE
Remove Boost dependency in wait_queue_test and example code

### ISSUE THREAD

**Issue by cliffg-softwarelibre** [connectivecpp/utility-rack#16]
Currently (Apr 2019) the only Boost dependency in the utility-rack repository is in the wait_queue_test and shared_buffer_demo.cpp. The wait_queue_test can be changed to use a different circular buffer, and the shared_buffer_demo app can be changed to use the utility marshalling facilities.

A good quality circular buffer to test with (in addition to Martin's ring-span-lite) is:

https://github.com/JustasMasiulis/circular_buffer

It is a high quality, STL style, single header container.

While Boost is an excellent, high quality set of libraries, it simplifies utility-rack dependency management not to have it as a dependency.

**Comment by oxenran** [comment]
I just submitted a merge request for the issue.

**Comment by oxenran** [comment]
#22
