### ISSUE TITLE
Add missing includes and std qualification to example programs

### ISSUE THREAD

**Issue by cliffg-softwarelibre** [connectivecpp/utility-rack#5]
The demo programs are missing includes, they happen to compile because <iostream> "gift includes" many other headers. Specifically (and this is not inclusive):

EXIT_SUCCESS: <cstdlib>
std::string: <string>
u_int64_t: should be std::uint64_t, the header is <cstdint>
std::byte: <cstddef>

**Comment by tgill880** [comment]
All done. Might have missed one or two.
